import { Course } from "./course";

export const courseData: Course[] = [
  { title: "JavaScript Drum Kit" },
  { title: "JS and CSS Clock" },
  { title: "CSS Variables" },
  { title: "Array Cardio Day 1" },
  { title: "Flex Panel Gallery" },
  { title: "Type Ahead" },
  { title: "Array Cardio Day 2" },
  { title: "Fun with HTML5 Canvas" },
  { title: "Dev Tools Domination" },
  { title: "Hold Shift and Check Checkboxes" },
  { title: "Custom Video Player" },
  { title: "Key Sequence Detection" },
  { title: "Slide in on Scroll" },
  { title: "JavaScript References VS Copying" },
  { title: "LocalStorage" },
  { title: "Mouse Move Shadow" },
  { title: "Sort Without Articles" },
  { title: "Adding Up Times with Reduce" },
  { title: "Webcam Fun" },
  { title: "Speech Detection" },
  { title: "Geolocation" },
  { title: "Follow Along Link Highlighter" },
  { title: "Speech Synthesis" },
  { title: "Sticky Nav" },
  { title: "Event Capture, Propagation, Bubbling and Once" },
  { title: "Stripe Follow Along Nav" },
  { title: "Click and Drag" },
  { title: "Video Speed Controller" },
  { title: "Countdown Timer" },
  { title: "Whack A Mole" }
];
